[2025-10-23T04:00:13.308+0000] {scheduler_job_runner.py:1586} WARNING - Marking task instance <TaskInstance: audio_processing_pipeline.model_validation manual__2025-10-23T03:49:16.161745+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
[2025-10-23T04:00:13.428+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: audio_processing_pipeline.model_validation manual__2025-10-23T03:49:16.161745+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
